### ISSUE TITLE
Add function to enhance the algorithm even more precise

### ISSUE THREAD

**Issue by fury-05** [fury-05/BookRecomendApp#2]
Looking for more enhancement in prediction

**Comment by Hithesh2022** [comment]
Hi i wanted to contribute i read the readme file
also while regestring for book api  Its asking to which purpouse i use Api 
user,publicdata ,Application data so which option should i select?

**Comment by Hithesh2022** [comment]
@fury-05 Hi i wanted to contribute i read the readme file
also while regestring for book api Its asking to which purpouse i use Api
user,publicdata ,Application data so which option should i select?

**Comment by fury-05** [comment]
For Contribution in Readme file you can add what you think is missing, then create a pull request I will review it and merge if no corrections are needed.

As for what purpose to select that is totally dependent on user as individual and api usage rules, you can refer to api documentation from the provider.
